export const ADMIN_ROUTES = {
  LOGIN: '/admin/login',
  DASHBOARD: '/admin',
  LEADS: '/admin/leads',
  LEAD_DETAILS: (id: string) => `/admin/leads/${id}`,
  EVENTS: '/admin/events',
  EVENT_NEW: '/admin/events/new',
  EVENT_DETAILS: (id: string) => `/admin/events/${id}`,
  EVENT_REGISTRATIONS: (id: string) => `/admin/events/${id}/registrations`,
  BLOGS: '/admin/blogs',
  BLOG_NEW: '/admin/blogs/new',
  BLOG_DETAILS: (id: string) => `/admin/blogs/${id}`,
  TESTIMONIALS: '/admin/testimonials',
  TESTIMONIAL_NEW: '/admin/testimonials/new',
  TESTIMONIAL_DETAILS: (id: string) => `/admin/testimonials/${id}`,
  USERS: '/admin/users',
  USER_NEW: '/admin/users/new',
  USER_DETAILS: (id: string) => `/admin/users/${id}`,
  SETTINGS: '/admin/settings',
  SETTINGS_GENERAL: '/admin/settings/general',
  SETTINGS_NOTIFICATIONS: '/admin/settings/notifications',
  SETTINGS_INTEGRATIONS: '/admin/settings/integrations',
} as const;
