export const URLS = {
  home: "/",
  about: "/about",
  studyIn: "/study-in",
  studyInCountry: (country: string) => `/study-in/${country}`,
  universities: "/universities",
  universityDetail: (slug: string) => `/universities/${slug}`,
  courses: "/courses",
  courseDetail: (slug: string) => `/courses/${slug}`,
  scholarships: "/scholarships",
  scholarshipDetail: (slug: string) => `/scholarships/${slug}`,
  services: "/services",
  resources: "/resources",
  events: "/events",
  blog: "/blog",
  successStories: "/success-stories",
  contact: "/contact",
  bookCounselling: "/book-counselling",
};
